let hatData = {
  hats: [
    {
      title: "Trollfjord Hat",
      ravelry_url: "https://ravel.me/angelaknitsnow/acth22",
      detail_url: "detail.html",
      image_thumb: "https://via.placeholder.com/300x400",
      image_full: "../images/IMG_1055.jprg",
      category: "Hat",
      startDate: "05/22/2021",
      endDate: "05/25/2021",
    },
    {
      title: "project 7",
      ravelry_url: "https://ravel.me/angelaknitsnow/acth22",
      detail_url: "#",
      image_thumb: "https://via.placeholder.com/300x400",
      image_full: "../images/IMG_1055.jprg",
      category: "Hat",
      startDate: "05/22/2021",
      detail_url: "#",
      endDate: "05/25/2021",
    },
    {
      title: "project 8",
      ravelry_url: "https://ravel.me/angelaknitsnow/acth22",
      detail_url: "#",
      image_thumb: "https://via.placeholder.com/300x400",
      image_full: "../images/IMG_1055.jprg",
      category: "Hat",
      startDate: "05/22/2021",
      detail_url: "#",
      endDate: "05/25/2021",
    },
  ],
};
