let projectData = {
  projects: [
    {
      title: "Murcia Shawl",
      ravelry_url: "https://ravel.me/angelaknitsnow/m1",
      detail_url: "#",
      image_thumb: "../images/thumb/MurciaShawl_thumb.jpeg",
      image_full: "../images/IMG_1055.jprg",
      craft: "knitting",
      category: "Shawl",
      startDate: "11/12/2021",
      endDate: "11/19/2021",
    },
    {
      title: "Bernie's Mittens",
      ravelry_url: "hhttps://ravel.me/angelaknitsnow/bm",
      detail_url: "#",
      image_thumb: "../images/thumb/MurciaShawl_thumb.jpeg",
      image_full: "../images/IMG_1055.jprg",
      category: "Mittens",
      startDate: "10/31/2021",
      endDate: "11/05/2021",
    },
    {
      title: "Nordic Mitts",
      ravelry_url: "https://ravel.me/angelaknitsnow/nm",
      detail_url: "#",
      image_thumb: "../images/thumb/MurciaShawl_thumb.jpeg",
      image_full: "../images/IMG_1055.jprg",
      category: "Mittens",
      startDate: "10/25/2021",
      endDate: "10/30/2021",
    },
    {
      title: "Lifes Rich tapestry",
      ravelry_url: "https://ravel.me/angelaknitsnow/lrt",
      detail_url: "#",
      image_thumb: "../images/thumb/MurciaShawl_thumb.jpeg",
      image_full: "../images/IMG_1055.jprg",
      category: "Shawl",
      startDate: "07/20/2021",
      endDate: "09/05/2021",
    },
    {
      title: "NightShift",
      ravelry_url: "https://ravel.me/angelaknitsnow/n3",
      detail_url: "#",
      image_thumb: "../images/thumb/MurciaShawl_thumb.jpeg",
      image_full: "../images/IMG_1055.jprg",
      category: "Shawl",
      startDate: "06/14/2021",
      endDate: "07/09/2021",
    },
    {
      title: "Trollfjord Hat",
      ravelry_url: "https://ravel.me/angelaknitsnow/acth22",
      detail_url: "#",
      image_thumb: "../images/thumb/MurciaShawl_thumb.jpeg",
      image_full: "../images/IMG_1055.jprg",
      category: "Hat",
      startDate: "05/22/2021",
      endDate: "05/25/2021",
    },
  ],
};
