let projectData = {
  projects: [
    {
      title: "Bernie Mittens",
      detail_url: "#",
      image_thumb: "../images/bernieMitts_300x400.jpg",
      image_full: "#",
      category: "mittens",
      alt_text: "Knitted Bernie Mittens in retro colors",
    },
    {
      title: "Buffalo Plaid",
      detail_url: "#",
      image_thumb: "../images/buffoloPlaid_300x400.jpg",
      image_full: "#",
      category: "hats",
      alt_text: "Knitted plaid hat",
    },
    {
      title: "Comfort Cowl",
      detail_url: "detail.html",
      image_thumb: "../images/comfortCowl_01_300x400.jpg",
      image_full: "../images/comfortCowl_01_1200x1600.jpg",
      category: "cowl/shawl",
      alt_text: "Knitted grey cowl with red geometrical shapes",
    },
    {
      title: "Dovetail Cowl",
      detail_url: "#",
      image_thumb: "../images/dovetail_01_300x400.jpg",
      image_full: "../images/dovetail_01_1200x1600.jpg",
      category: "cowl/shawl",
      alt_text: "Knitted cowl in medium and light grey",
    },
    {
      title: "Life's Rich Tapestry",
      detail_url: "#",
      image_thumb: "../images/lifesRichTapestry_01_300x400.jpg",
      image_full: "../images/lifesRichTapestry_01_1200x1600.jpg",
      category: "cowl/shawl",
      alt_text: "Knitted shawl in multi color yarn",
    },
    {
      title: "Lyre Beanie",
      detail_url: "#",
      image_thumb: "../images/LyreBeanie_300x400.jpg",
      image_full: "#",
      category: "hat",
      alt_text: "Gray knitted hat with fair isle colorwork",
    },
    {
      title: "Murcia Shwal",
      detail_url: "#",
      image_thumb: "../images/murcia_01_300x400.jpg",
      image_full: "../images/murcia_01_1200x1600.jpg",
      category: "cowl/shawl",
      alt_text: "Knitted pink tweed lace shawl",
    },
    {
      title: "Nightshift",
      detail_url: "#",
      image_thumb: "../images/nightshift_01_300x400.jpg",
      image_full: "../images/nightshift_01_1200x1600.jpg",
      category: "cowl/shawl",
      alt_text: "Knitted multicolor mosaic shawl",
    },
    {
      title: "Noble Cowl",
      detail_url: "#",
      image_thumb: "../images/noble_01_300x400.jpg",
      image_full: "../images/noble_01_1200x1600.jpg",
      category: "cowl/shawl",
      alt_text: "Knitted lace cowl",
    },
    {
      title: "Nordic Mittens",
      detail_url: "#",
      image_thumb: "../images/nordicMitts_300x400.jpg",
      image_full: "#",
      category: "mittens",
      alt_text: "Purple knitted mittens",
    },
    {
      title: "Tied Knots Hat",
      detail_url: "#",
      image_thumb: "../images/tiedKnots_300x400.jpg",
      image_full: "#",
      category: "hat",
      alt_text: "Knitted hat with cablework",
    },
    {
      title: "Trollfjord Hat",
      detail_url: "#",
      image_thumb: "../images/trollfjordHat_300x400.jpg",
      image_full: "#",
      category: "hat",
      alt_text: "Knitted hat with fair isle colorwork",
    },
  ],
};
